#include <hmg.ch>
/*************************************************************************************************************************
 * Sequencia de tarefas a serem realizadas
 * Desenvolvido por Ceu Azul Tecnologia
 * Programador responsavel Crocciari Daniel
 * Cedido para HMGLights
 * OpenSource/Freeware
 * 2019 
 *************************************************************************************************************************
 */

function inclui_produtos()

	// adiciona produtos no vetor de produtos
	AADD(paProdutos, { "001","batata frita" } )
	AADD(paProdutos, { "002","batata frita rustica" } )
	AADD(paProdutos, { "003","kibe frito" } )
	AADD(paProdutos, { "004","kibe frito recheado" } )
	AADD(paProdutos, { "005","frango a passarinho" } )
	AADD(paProdutos, { "006","nuggets de frango" } )
	AADD(paProdutos, { "007","salada verde" } )
	AADD(paProdutos, { "008","salada de tomate" } )
	AADD(paProdutos, { "009","salada grega" } )
	AADD(paProdutos, { "010","suco de laranja" } )
	AADD(paProdutos, { "011","suco de limao" } )
	AADD(paProdutos, { "012","suco de maracuja" } )	
		
return nil