#include <hmg.ch>
/*************************************************************************************************************************
 * Sequencia de tarefas a serem realizadas
 * Desenvolvido por Ceu Azul Tecnologia
 * Programador responsavel Crocciari Daniel
 * Cedido para HMGLights
 * OpenSource/Freeware
 * 2019 
 *************************************************************************************************************************
 */

function sobre()

	msgInfo( "Sequencia de tarefas"+chr(30)+chr(13)+;
			 "HMGLights"+chr(30)+chr(13)+chr(30)+chr(13)+;
			 "desenvolvido e cedido por"+chr(30)+chr(13)+;
			 "CAT Ceu Azul Tecnologia"+chr(30)+chr(13)+;
			 "Crocciari, Daniel"+chr(30)+chr(13)+chr(30)+chr(13)+;
			 "2019 OpenSource/Freeware",;
			 "Sobre...")


return nil


